// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"time"
)

type Order struct {
	ID               int64
	Description      string
	TransactionDate  time.Time
	TransactionValue float64
}
